# Generated by Django 3.2.5 on 2021-07-25 15:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to=account.models.path_and_rename),
        ),
    ]
