# Generated by Django 3.2.4 on 2021-06-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_state',
            field=models.CharField(
                choices=[('ไม่มีสิทธิ์จอง', 'ไม่มีสิทธิ์จอง'), ('มีสิทธิ์จอง', 'มีสิทธิ์จอง'), ('รอยืนยัน', 'รอยืนยัน'),
                         ('ยืนยัน', 'ยืนยัน')], default='ไม่มีสิทธิ์จอง', max_length=14, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='students/'),
        ),
    ]
