# Generated by Django 3.2.4 on 2021-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='บัญชีธนาคาร'),
        ),
        migrations.AddField(
            model_name='account',
            name='car_registration',
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name='ป้ายทะเบียนยนต์'),
        ),
        migrations.AddField(
            model_name='account',
            name='motorcycle_registration',
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name='ป้ายทะเบียนรถจักรยานยนต์'),
        ),
        migrations.AddField(
            model_name='account',
            name='room_number',
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name='เลขห้อง'),
        ),
    ]
