# Generated by Django 3.2.4 on 2021-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20210701_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_state',
            field=models.CharField(choices=[('ไม่มีสิทธิ์จอง', 'ไม่มีสิทธิ์จอง'), ('มีสิทธิ์จอง', 'มีสิทธิ์จอง')],
                                   default='ไม่มีสิทธิ์จอง', max_length=14, verbose_name='สถานะ'),
        ),
    ]
