# Generated by Django 3.2.4 on 2021-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_alter_account_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='booking_state',
            field=models.BooleanField(default=False, verbose_name='สถานะการจอง'),
        ),
    ]
