# Generated by Django 3.2.4 on 2021-07-01 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_account_booking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='room_number',
        ),
    ]
