# Generated by Django 3.2.4 on 2021-07-02 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_remove_account_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='booking_state',
            new_name='is_booking_state',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
