# Generated by Django 3.2.5 on 2021-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210710_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='วันเกิด'),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name_en',
            field=models.CharField(
                max_length=100, null=True, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name_en',
            field=models.CharField(
                max_length=100, null=True, verbose_name='นามสกุลภาษาอังกฤษ'),
        ),
    ]
