# Generated by Django 3.2.5 on 2021-07-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210712_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(
                max_length=200, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(null=True, verbose_name='วันเกิด'),
        ),
    ]
