# Generated by Django 3.2.3 on 2021-06-16 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('dorm', '0005_auto_20210616_1520'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Booking',
			fields=[
				('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				('date', models.DateTimeField(auto_now_add=True)),
				('room',
				 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_room',
								   to='dorm.room')),
				('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
										   to=settings.AUTH_USER_MODEL)),
			],
		),
	]
