# Generated by Django 3.2.6 on 2021-08-31 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='opening_booking',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='booking.academic_year', verbose_name='ปีการศึกษา'),
        ),
    ]
