# Generated by Django 3.2.4 on 2021-07-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0002_auto_20210621_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_day', models.DateTimeField(verbose_name='เวลาเปิดจอง')),
                ('closed_day', models.DateTimeField(verbose_name='เวลาปิดจอง')),
                ('group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group')),
            ],
        ),
    ]
