# Generated by Django 3.2.4 on 2021-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0003_opening_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_booking',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
