# Generated by Django 3.2.4 on 2021-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0004_opening_booking_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_booking',
            name='academic_year',
            field=models.CharField(default=0.000390015600624025, max_length=10, verbose_name='ปีการศึกษา'),
            preserve_default=False,
        ),
    ]
