# Generated by Django 3.2.4 on 2021-07-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('dorm', '0006_dormitory_images_room_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_auto_20210701_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_room',
                                    to='dorm.room', verbose_name='เลขห้อง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_user',
                                    to=settings.AUTH_USER_MODEL, verbose_name='คนจอง'),
        ),
        migrations.CreateModel(
            name='Room_confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('is_confirmation', models.BooleanField(
                    null=True, verbose_name='สถานะการยืนยัน')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('room',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_room',
                                   to='dorm.room', verbose_name='เลขห้อง')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_user',
                                   to=settings.AUTH_USER_MODEL, verbose_name='คนจอง')),
            ],
        ),
    ]
