# Generated by Django 3.2.4 on 2021-07-10 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210710_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_booking',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
