# Generated by Django 3.2.3 on 2021-05-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Dormitory',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100)),
			],
		),
		migrations.CreateModel(
			name='Room',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('floor', models.PositiveIntegerField(default=1, verbose_name='ชั้น')),
				(
				'room_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='เลขห้อง')),
				('room_type', models.CharField(choices=[('MALE', 'ผู้ชาย'), ('FEMALE', 'ผู้หญิง')], max_length=10,
											   verbose_name='ประเภทห้องพัก')),
				('amount', models.PositiveIntegerField(default=3, verbose_name='จำนวน')),
				('status_room', models.BooleanField(default=False, verbose_name='สถานะของห้อง')),
				('dorm_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dormitory',
												to='dorm.dormitory', verbose_name='ชื่อหอพัก')),
			],
		),
	]
