# Generated by Django 3.2.3 on 2021-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_auto_20210603_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/dorm/'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
