# Generated by Django 3.2.3 on 2021-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_auto_20210603_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='images',
            field=models.ImageField(
                blank=True, null=True, upload_to='images/dorm/'),
        ),
    ]
