# Generated by Django 3.2.4 on 2021-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dorm', '0005_auto_20210616_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='images_room_plan',
            field=models.ImageField(
                blank=True, null=True, upload_to='images/dorm/room_plan/'),
        ),
    ]
