# Generated by Django 3.2.4 on 2021-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dorm', '0006_dormitory_images_room_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
